#ifndef AGX_INCLUDE_GUARD
#define AGX_INCLUDE_GUARD

// Adapted from Troy Sobotka's AgX: https://github.com/sobotka/AgX
// LUT generated by xirreal. See THIRD_PARTY_NOTICES.md for provenance and terms.

#define AGX_LUT_BLOCK_SIZE 32
#define AGX_LUT_DIMENSIONS ivec2(AGX_LUT_BLOCK_SIZE * AGX_LUT_BLOCK_SIZE, AGX_LUT_BLOCK_SIZE)
#define AGX_LUT_PIXEL_SIZE (1.0 / vec2(AGX_LUT_DIMENSIONS))

vec3 agx_powsafe(vec3 color, float power) {
   return pow(abs(color), vec3(power)) * sign(color);
}

vec3 agx_apply_matrix(vec3 color, mat3 m) {
   return vec3(
      dot(color, m[0]),
      dot(color, m[1]),
      dot(color, m[2])
   );
}

const mat3 AGX_INSET_MATRIX = mat3(
      vec3(0.84247906, 0.0784336, 0.07922375),
      vec3(0.04232824, 0.87846864, 0.07916613),
      vec3(0.04237565, 0.0784336, 0.87914297)
   );

const mat3 AGX_OUTSET_MATRIX = mat3(
      vec3(1.1968790, -0.09802088, -0.09902975),
      vec3(-0.05289685, 1.15190313, -0.09896118),
      vec3(-0.05297163, -0.09804345, 1.15107368)
   );

vec3 agxLog(vec3 color) {
   color = max(vec3(0.0), color);

   color = agx_apply_matrix(color, AGX_INSET_MATRIX);

   float minEV = -10.0;
   float maxEV = 6.5;
   float midGrey = 0.18;

   color = max(vec3(0.0), color);

   color = mix(color, vec3(1.525878e-5) + color, lessThan(color, vec3(3.051757e-5)));
   color = clamp(log2(color / midGrey), vec3(minEV), vec3(maxEV));
   color = (color - minEV) / (maxEV - minEV);

   color = clamp(color, 0.0, 1.0);
   return color;
}

vec3 agxLutSample(vec3 color, sampler2D lut) {
   vec3 lut3D = color * float(AGX_LUT_BLOCK_SIZE - 1);
   vec2 lut2D_front;
   lut2D_front.x = floor(lut3D.z) * float(AGX_LUT_BLOCK_SIZE) + lut3D.x;
   lut2D_front.y = lut3D.y;

   vec2 lut2D_back;
   lut2D_back.x = ceil(lut3D.z) * float(AGX_LUT_BLOCK_SIZE) + lut3D.x;
   lut2D_back.y = lut3D.y;

   lut2D_front = (lut2D_front + 0.5) * AGX_LUT_PIXEL_SIZE;
   lut2D_back = (lut2D_back + 0.5) * AGX_LUT_PIXEL_SIZE;

   vec3 result = mix(
         texture(lut, lut2D_front).rgb,
         texture(lut, lut2D_back).rgb,
         fract(lut3D.z)
      );

   result = agx_powsafe(result, 2.2);

   return result;
}

vec3 agxOutset(vec3 color) {
   return agx_apply_matrix(color, AGX_OUTSET_MATRIX);
}

vec3 agx_srgbOETF(vec3 color) {
   return mix(
      12.92 * color,
      1.055 * pow(color, vec3(1.0 / 2.4)) - 0.055,
      step(vec3(0.0031308), color)
   );
}

vec3 agxTonemap(vec3 color, sampler2D lut) {
   color = agxLog(color);
   color = agxLutSample(color, lut);
   return color;
}

vec3 agxTonemapOutset(vec3 color, sampler2D lut) {
   color = agxTonemap(color, lut);
   color = agxOutset(color);
   return color;
}

vec3 agxComplete(vec3 srgbLinear, sampler2D lut) {
   vec3 color = agxTonemapOutset(srgbLinear, lut);
   color = max(vec3(0.0), color);
   color = agx_srgbOETF(color);

   return color;
}

#endif
