block.1 = water flowing_water

block.2 = minecraft:leaf_litter minecraft:sugar_cane %minecraft:crops minecraft:pumpkin minecraft:melon minecraft:bush %minecraft:leaves minecraft:short_grass minecraft:tall_grass %minecraft:underwater_bonemeals %c:flowers %minecraft:flowers minecraft:vine %minecraft:saplings minecraft:fern minecraft:firefly_bush minecraft:cactus minecraft:dead_bush %minecraft:wool
