iris.features.required=COMPUTE_SHADERS SSBO REVERSED_CULLING CUSTOM_IMAGES
shadow.enabled=true
shadow.culling=false

separateAo=true

# mode 0 = ReSTIR, mode 1 = Reference PT, mode 2 = BVH debug, mode 3 = nothing
#if MODE != 0
# TODO: add additional passes to disable here
#endif
#if MODE != 1
program.composite3.enabled=false
#endif
#if MODE != 2
program.composite2.enabled=false
#endif
program.prepare99.enabled=ENABLE_SORT_VALIDATION
program.composite1.enabled=ENABLE_QUAD_VALIDATION
program.composite99.enabled=ENABLE_DEBUG_OVERLAY

# Quad data buffers
#   bufferObject.0  = 4 + 32 * MAX_QUAD_COUNT  (QuadDataBuffer: 4-byte counter + 32-byte QuadData)
#   bufferObject.2  =     24 * MAX_QUAD_COUNT  (AABBBuffer)
#   bufferObject.3  =      4 * MAX_QUAD_COUNT  (MortonCodeBuffer)
#   bufferObject.4  =      4 * MAX_QUAD_COUNT  (ClusterIndexBuffer)
#   bufferObject.5  =      4 * MAX_QUAD_COUNT  (ParentIDBuffer)
#   bufferObject.6  =     64 * (MAX_QUAD_COUNT - 1)  (BVH2NodeBuffer: N-1 internal nodes)
#   bufferObject.7  =      9 * MAX_QUAD_COUNT  (SortScratchBuffer: keys + vals + pass hist + global hist, with slack)
#   bufferObject.10 =     48 * MAX_QUAD_COUNT  (QuadPosBuffer)

#if MAX_QUAD_COUNT == 1048576
bufferObject.0  = 33554436
bufferObject.2  = 25165824
bufferObject.3  = 4194304
bufferObject.4  = 4194304
bufferObject.5  = 4194304
bufferObject.6  = 67108800
bufferObject.7  = 9437184
bufferObject.10 = 50331648
#elif MAX_QUAD_COUNT == 2097152
bufferObject.0  = 67108868
bufferObject.2  = 50331648
bufferObject.3  = 8388608
bufferObject.4  = 8388608
bufferObject.5  = 8388608
bufferObject.6  = 134217664
bufferObject.7  = 18874368
bufferObject.10 = 100663296
#elif MAX_QUAD_COUNT == 4194304
bufferObject.0  = 134217732
bufferObject.2  = 100663296
bufferObject.3  = 16777216
bufferObject.4  = 16777216
bufferObject.5  = 16777216
bufferObject.6  = 268435392
bufferObject.7  = 37748736
bufferObject.10 = 201326592
#elif MAX_QUAD_COUNT == 8388608
bufferObject.0  = 268435460
bufferObject.2  = 201326592
bufferObject.3  = 33554432
bufferObject.4  = 33554432
bufferObject.5  = 33554432
bufferObject.6  = 536870848
bufferObject.7  = 75497472
bufferObject.10 = 402653184
#elif MAX_QUAD_COUNT == 16777216
bufferObject.0  = 536870916
bufferObject.2  = 402653184
bufferObject.3  = 67108864
bufferObject.4  = 67108864
bufferObject.5  = 67108864
bufferObject.6  = 1073741760
bufferObject.7  = 150994944
bufferObject.10 = 805306368
#elif MAX_QUAD_COUNT == 33554432
bufferObject.0  = 1073741828
bufferObject.2  = 805306368
bufferObject.3  = 134217728
bufferObject.4  = 134217728
bufferObject.5  = 134217728
bufferObject.6  = 2147483584
bufferObject.7  = 301989888
bufferObject.10 = 1610612736
#endif
# oversized control buffer so i dont crash iris again oops :3
bufferObject.1 = 512
# texture infos (16 bytes * 65536 entries + 4 bytes)
bufferObject.8 = 1048580
# texture data (4 bytes * 268435456 texels = 1GiB)
bufferObject.9 = 1073741824

# sort upsweep/downsweep passes
indirect.prepare = 1 24
indirect.prepare2 = 1 0
indirect.prepare4 = 1 0
indirect.prepare5 = 1 0
indirect.prepare7 = 1 0
indirect.prepare8 = 1 0
indirect.prepare10 = 1 0
indirect.prepare11 = 1 0
indirect.prepare13 = 1 0
indirect.prepare14 = 1 24
indirect.prepare99 = 1 24

# hploc build
indirect.composite = 1 12

customTexture.blockAtlas = minecraft:textures/atlas/blocks.png
customTexture.normalAtlas = minecraft:textures/atlas/blocks_n.png
customTexture.specularAtlas = minecraft:textures/atlas/blocks_s.png
customTexture.agxLut = /lib/post/agx_lut.dat TEXTURE_2D RGB16 1024 32 RGB UNSIGNED_SHORT

image.transmittanceImg = transmittanceLUT rgba rgba32f float false false 512 128
image.multiScatteringImg = multiScatteringLUT rgba rgba32f float false false 64 64
image.skyViewImg = skyViewLUT rgba rgba32f float false false 400 400

screen = MODE [PT_OPTIONS] MAX_QUAD_COUNT ALPHA_TEST ENTITY_TEXTURES ENTITY_PBR [DEBUG]
sliders = DOF_FOCAL_LENGTH DOF_FSTOP DOF_FOCUS_DISTANCE DOF_SENSOR_WIDTH DOF_BLADES GLASS_CAUSTIC_SAMPLES GLASS_CAUSTIC_CONE_DEGREES GLASS_CAUSTIC_FILTER GLASS_CAUSTIC_CLAMP

screen.PT_OPTIONS = DOF_ENABLED DOF_AUTOFOCUS DOF_FOCAL_LENGTH DOF_FSTOP DOF_FOCUS_DISTANCE DOF_SENSOR_WIDTH DOF_BLADES GLASS_CAUSTICS GLASS_CAUSTIC_SAMPLES GLASS_CAUSTIC_CONE_DEGREES GLASS_CAUSTIC_FILTER GLASS_CAUSTIC_CLAMP
screen.DEBUG = ENABLE_QUAD_VALIDATION ENABLE_SORT_VALIDATION ENTITY_TEXTURES_DEBUG ENABLE_DEBUG_OVERLAY WG_SIZE

uniform.int.randomSeed = randomInt()
