iris.features.required=COMPUTE_SHADERS SSBO REVERSED_CULLING
shadow.enabled=true
shadow.culling=reversed

# vertex/quad buffer
# 16 + 32 * MAX_VERTEX_COUNT = 16 + 32 * 33554432 = 1073741840 bytes
bufferObject.0 = 1073741840

# oversized control buffer so i dont crash iris again oops :3
bufferObject.1 = 256

# AABBs (32 bytes per quad)
bufferObject.2 = 268435456

# mormon codes (4 bytes per quad)
bufferObject.3 = 33554432

# cluster indices (4 bytes per quad)
bufferObject.4 = 33554432

# pIDs (4 bytes per quad)
bufferObject.5 = 33554432

# BVH2 nodes (32 bytes each)
bufferObject.6 = 268435424

# sort scratch (ping-pong + histogram + totals)
bufferObject.7 = 75497472

# sort upsweep/downsweep passes
indirect.prepare1 = 1 40
indirect.prepare3 = 1 40
indirect.prepare4 = 1 40
indirect.prepare6 = 1 40
indirect.prepare7 = 1 40
indirect.prepare9 = 1 40
indirect.prepare10 = 1 40
indirect.prepare12 = 1 40
indirect.prepare13 = 1 40
indirect.prepare15 = 1 40
indirect.prepare16 = 1 40
indirect.prepare18 = 1 40
indirect.prepare19 = 1 40
indirect.prepare21 = 1 40
indirect.prepare22 = 1 40
indirect.prepare24 = 1 40
indirect.prepare25 = 1 40

# hploc build
indirect.composite = 1 52
